# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: ì´ ì›í˜•
title: ê²Œì„ ì„œë²„ ê°œë°œì
email: upian12@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  Upian
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ğŸ“: 010 8729 4585  
  ğŸ“§: upian12@gmail.com
  
  <mark> skill </mark>
  C++, C#, Python
  DB: MSSQL, PostgreSQL, MYSQL, redis, MongoDB
  PHP, JavaScript

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ë°ì´ë¸Œë ˆì´í¬ê²Œì„ì»´í¼ë‹ˆì•„ì‹œì•„
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: ê²Œì„ ì„œë²„ ê°œë°œì
        caption: 2018.08 - 2019.09
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            H1Z1 ê°œë°œ

      - layout: left
        title: ì¡°ì´ì‹œí‹°
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: ê²Œì„ ì„œë²„ ê°œë°œì
        caption: 2020.01 - 2025.01
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            3on3FreeStyle
            JoyTown

  
########################################################################################################################################
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: H1Z1
        sub_title: ë°ì´ë¸Œë ˆì´í¬ê²Œì„ì»´í¼ë‹ˆì•„ì‹œì•„ (2018.08 - 2019.09)
        quote: >
          ê²Œì„ ì„œë²„ ì½˜í…ì¸  ë° íˆ´ ê°œë°œ
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

      - layout: top-middle
        title: 3on3FreeStyle
        sub_title: ì¡°ì´ì‹œí‹° (2020.01 - 2022.07)
        quote: >
          ê²Œì„ ì„œë²„ ì½˜í…ì¸  ë° íˆ´ ê°œë°œ
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

      - layout: top-middle
        title: Super awesome project
        sub_title: ì¡°ì´ì‹œí‹° (2022.07 - 2025.01)
        quote: >
          ê²Œì„ ì„œë²„ ë° íˆ´ ê°œë°œ
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

########################################################################################################################################
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ê°•ì›ëŒ€í•™êµ
        caption: 2012.03 - 2018.09
        sub_title: ì „ìí†µì‹ ê³µí•™ ì „ê³µ
        quote: >
          
        description: | # this will include new lines to allow paragraphs

########################################################################################################################################
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
########################################################################################################################################
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
